"""
Django settings for Inversiones368 project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from django.contrib.messages import constants as messages
import firebase_admin
from firebase_admin import storage,credentials
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-66r00@k6q9-54!5@(fnt-ox+mw%!xykd))hq3mc74j5cxp5%&p'


#*CORS // 
#* En caso de trabajar en codespaces, agregar url del codespace
ALLOWED_HOSTS = ['*']

CORS_ALLOWED_ORIGINS = [
    # Other trusted origins...
    '*'
]

CSRF_TRUSTED_ORIGINS = [
    # Other trusted origins...
    'https://localhost:8000',
    'https://renzocm-urban-carnival-6w464694qxrhxp4-8000.preview.app.github.dev',
    'https://bug-free-goggles-vwq4q46q9x63w6gr-8000.app.github.dev',
    'https://localhost:8000',
    'https://effective-system-wx9wxqjxvgph9x4w-8000.app.github.dev',
]

CSRF_USE_SESSIONS = True
CSRF_COOKIE_HTTPONLY = True

#*API_URLS
API_URL = "https://inversiones-368.onrender.com/api/v1"

#*Imagenes, Css, Js, etc
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

#*Redirecciones en caso de Login, Logout
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"
LOGIN_URL = 'home'


#* Registrar las aplicaciones/módulos creados 
INSTALLED_APPS = [
    # MODULOS DJANGO
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # MODULOS DE TERCEROS
    'widget_tweaks',
    # MODULOS PROPIOS
    'modulos.autenticacion',
    'modulos.seguridad',
    'modulos.sistema',
    'modulos.administracion',
    'modulos.proyectos',
    'modulos.usuarios',
    'modulos.proveedores',
    'modulos.almacen',
]


#* Firebase dataconfig
FIREBASE_CONFIG = {
  'apiKey': "AIzaSyCZ4MGmEmGOPIm5CW2xYWXRuQ87JcmcxNQ",
  'authDomain': "inversiones368-abce4.firebaseapp.com",
  'projectId': "inversiones368-abce4",
  'storageBucket': "inversiones368-abce4.appspot.com",
  'messagingSenderId': "467764746226",
  'appId': "1:467764746226:web:0f5c91e858ef2c09eb3d6b",
  'measurementId': "G-TLHC0RC5N6",
  "type": "service_account",
  "project_id": "inversiones368-abce4",
  "private_key_id": "b4ecdb8d5e6ea435eb1d5a18d99eb0b2939b3412",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDHGRwaMt550hn0\npUsqhy9QL+1gBIWOvgZiYcl2Cb/hLyAL6YEOwcgSBp2dEz6x4ORsa4j7qJCpRE3M\n8LyDpuQMEjREFhg5CU3+mFjpamhwHvkPfDIy/KgduFg9pU0CA9X3Al+ue/ToibKJ\n5NFto7DDsEn37hxxQWJo4+KVk71hdFeypdd63QtLhvf75wooTkXaDP2R5pDqrAkj\nB4e8jeLvfxjRbKPYlg2/HrKuhr6cUkfVVbsRZPNU/AWuvHTlkrprSZKv5b2FeYf2\nDqim+btX7VwWS/5+QuMzN2IrKCAM9RxRPT9Tm4ybVDFUVwwJqCFgyVXBY8CzMuBO\n+XYZHflhAgMBAAECggEAEnjlbxbWJmZUayrk4PK+9Ikl1HlG7Pn7fKhG+VEpQNrO\n9dv50eUvy2BawkaVVAqiFt8ZTAQVO+cu8rtJOkvDL82GlOSZ5bzTxDHdWfa57uEo\nyYOD4tAnRu6iHUIXdX7mnK7XMsikbejMrFeTCMGdtmJGUp8Ae4+N8l5mWOtmsEJh\ntd4xgZlBjX9INWlbTdY+3VhcQfwoAHkYyv5jsaqFMvhiHOyWxmT7WnONw4p52W4F\nfcZFem3EBlTYKwt6YYO5ts7dbauYThnUmy2lQbcuJ0xvZZ8m+0xAIlPgmjHrqctx\n4zxM2EfgN8TF3xQo9EVfvhRrt6KTaPhOuzP0qvSI2QKBgQDiwH5za3W9cXUvTPkN\nXr18HMOYR0RQqY8FC/7p45+sbRbdJxZ/v8N9ulZ1zP+kd8SfFtpkd8eb7WF0hfcn\nzpTbxlenN36xhNhdlnw5jxrJS8riINDFqPFCd9GlbBsZ+7+QywzuU/OLKrP5vO0Z\n2alYSjIASuLKs3uNBzL+1EG2ZQKBgQDgx3d5ScmlxVH7AgPJf80XI8Yo91bIuM36\nzX7Ec9BjtMHoCcs3vPd0UYmk+UNYCVGld/4IXdHdiXWJ2/iKylHfzPsA+5yfWbt4\nbgCYlyWz/YAlCYUMZZzuBxMtuTKgZ0K8eyENFcV/fJVJLNpV3cx5KPDPB42cUfPs\nIWmjCZ1ZTQKBgQDJ+NnpZvNl/dR6gF5qWVQAZAKY9gnUq2NYBHpXzMeiJz0xWarB\nuYagy8RNg37F+WRqrEl1KffjXMrsppMiovCW3hGfQWAZMRIkMnGON3iNinQ5fS9Y\nkIXtRZq4dRWizEmy6Bopgx+weyX6Mh0jZGxh1xy4g/uEv+AyGxKCR4AMvQKBgQCV\ngVZf38o1bib28wId1dlNmMfGm6ynWPP36xJ0DCwBBUsr0MfPzOox/cG1bu1x8tDR\nZBwc6HocBb+d8CdB+Qu39ZjFsJUeEAr3MQNIes/jBatj9w79jeBxGVeSQ+n+cnAa\n+TKkh2STRQPuZdza2+mSdL6mlPmFjaTV2+ttO4niyQKBgQDY/zVnaqSOuo2NVbl/\nUeOeGNc7F6VfVVQybZNJ/9mb9yfFkCSYucR7gz/7Md3vMlZLB7GDX/uXluq6lHhh\nKrVB4T42bkSyS/mRzdpbBhOPY6wq9VI/3tfODRIy8tTApBHwFvEInZJ5evltEy84\nuVL0OjPkuwWP2VQbniuDq23PCw==\n-----END PRIVATE KEY-----\n",
  "client_email": "firebase-adminsdk-opwg8@inversiones368-abce4.iam.gserviceaccount.com",
  "client_id": "109140170863181146954",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-opwg8%40inversiones368-abce4.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}

cred = credentials.Certificate(FIREBASE_CONFIG)
firebase_admin.initialize_app(cred)

X_FRAME_OPTIONS = 'SAMEORIGIN' #Antes de los MIDDLEWARE

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Inversiones368.urls'

#* Asignación de la carpeta Templates para poner las plantillas
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["Templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'helpers.user.load_usuario',
                'helpers.user.menu'
            ],
        },
    },
]

WSGI_APPLICATION = 'Inversiones368.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#*Tipos de mensaje
MESSAGE_TAGS = {
    messages.DEBUG: "primary ",
    messages.INFO: "info",
    messages.SUCCESS: "success",
    messages.WARNING: "warning",
    messages.ERROR: "warning"
}
# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-PE'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')